import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";




export const metadata: Metadata = {
  title: "Pixelbid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#F6E9B2' }}>
        <Navbar />
        <main style={{ backgroundColor: '#F6E9B2' }} className="container mx-auto px-5 pt-10">
          {children}
        </main>
      </body>
    </html>
  );
}
